<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="shreya-PC" failures="1" tests="8" name="com.qa.opencart.test.ProductInfoTest" time="96.522" errors="0" timestamp="11 Oct 2021 14:57:32 GMT" skipped="3">
  <testcase classname="com.qa.opencart.test.ProductInfoTest" name="productMetatadataTest" time="6.071">
    <failure message="The following asserts failed:
	expected [$2,000.00] but found [null],
	expected [$2,000.00] but found [null],
	expected [$2,000.00] but found [null],
	expected [$2,000.00] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [$2,000.00] but found [null],
expected [$2,000.00] but found [null],
expected [$2,000.00] but found [null],
expected [$2,000.00] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.qa.opencart.test.ProductInfoTest.productMetatadataTest(ProductInfoTest.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- productMetatadataTest -->
  <testcase classname="com.qa.opencart.test.ProductInfoTest" name="productImageCountTest" time="24.797"/>
  <testcase classname="com.qa.opencart.test.ProductInfoTest" name="productMetatadataTest" time="11.964">
    <skipped/>
  </testcase> <!-- productMetatadataTest -->
  <testcase classname="com.qa.opencart.test.ProductInfoTest" name="productImageCountTest" time="16.833"/>
  <testcase classname="com.qa.opencart.test.ProductInfoTest" name="productImageCountTest" time="9.194"/>
  <testcase classname="com.qa.opencart.test.ProductInfoTest" name="productMetatadataTest" time="6.528">
    <skipped/>
  </testcase> <!-- productMetatadataTest -->
  <testcase classname="com.qa.opencart.test.ProductInfoTest" name="productHeaderTest" time="13.790"/>
  <testcase classname="com.qa.opencart.test.ProductInfoTest" name="productMetatadataTest" time="7.345">
    <skipped/>
  </testcase> <!-- productMetatadataTest -->
</testsuite> <!-- com.qa.opencart.test.ProductInfoTest -->
